services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=chatapp
      - MONGO_INITDB_ROOT_PASSWORD=chatapp
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8010:8010
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=chatapp
      - ME_CONFIG_MONGODB_ADMINPASSWORD=chatapp
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo: {}


